# Generated by Django 5.2.4 on 2025-12-18 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-is_primary', 'upload_date']},
        ),
        migrations.RemoveField(
            model_name='image',
            name='folder_location',
        ),
        migrations.RemoveField(
            model_name='image',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='image',
            name='tags',
        ),
        migrations.AddField(
            model_name='image',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('range', models.CharField(blank=True, max_length=255, null=True)),
                ('folder_location', models.CharField(blank=True, max_length=500, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tags', models.ManyToManyField(blank=True, to='tags.tag')),
            ],
            options={
                'verbose_name_plural': 'Entries',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.AddField(
            model_name='image',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='image_upload.entry'),
        ),
    ]
