# Generated by Django 5.2.4 on 2025-12-18 11:45

from django.db import migrations
import uuid
import os


def migrate_images_to_entries(apps, schema_editor):
    """
    Convert existing Image records to Entry + Image pairs.
    Each Image becomes an Entry with one Image that has is_primary=True.
    """
    Image = apps.get_model('image_upload', 'Image')
    Entry = apps.get_model('image_upload', 'Entry')
    Tag = apps.get_model('tags', 'Tag')
    
    # Get all existing images
    images = Image.objects.all()
    
    for old_image in images:
        # Create a new Entry with the metadata from the Image
        entry = Entry.objects.create(
            name=old_image.name,
            publisher=old_image.publisher,
            range=old_image.range,
            folder_location=getattr(old_image, 'folder_location', None),
            upload_date=old_image.upload_date,
            notes=getattr(old_image, 'notes', None),
        )
        
        # Copy tags from Image to Entry (many-to-many)
        if hasattr(old_image, 'tags'):
            for tag in old_image.tags.all():
                entry.tags.add(tag)
        
        # Update the Image to link to the Entry
        old_image.entry = entry
        old_image.is_primary = True  # First image is always primary
        
        # Rename the file from _initial suffix to _uuid suffix
        if old_image.image:
            old_path = old_image.image.path
            if os.path.exists(old_path):
                # Get file extension
                base, ext = os.path.splitext(old_path)
                
                # Generate new filename with UUID
                unique_id = uuid.uuid4().hex[:8]
                publisher = old_image.publisher or 'unknown'
                range_name = old_image.range or 'unknown'
                name = old_image.name or 'unknown'
                
                # Convert to camelCase
                def to_camel_case(text):
                    if not text:
                        return 'unknown'
                    words = text.replace('-', ' ').replace('_', ' ').split()
                    if not words:
                        return 'unknown'
                    return words[0].lower() + ''.join(word.capitalize() for word in words[1:])
                
                publisher_cc = to_camel_case(publisher)
                range_cc = to_camel_case(range_name)
                name_cc = to_camel_case(name)
                
                new_filename = f"{publisher_cc}_{range_cc}_{name_cc}_{unique_id}{ext}"
                new_path = os.path.join(os.path.dirname(old_path), new_filename)
                
                # Rename the file
                try:
                    os.rename(old_path, new_path)
                    # Update the image field
                    old_image.image.name = f"uploaded_images/{new_filename}"
                except Exception as e:
                    print(f"Error renaming file {old_path}: {e}")
        
        old_image.save()


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration by converting Entries back to standalone Images.
    This will delete Entries and restore the Image model structure.
    """
    Image = apps.get_model('image_upload', 'Image')
    Entry = apps.get_model('image_upload', 'Entry')
    
    # This is complex to reverse, so we'll just clear the entries
    # In production, you'd want more sophisticated logic
    for image in Image.objects.all():
        if image.entry:
            # Copy entry data back to image
            image.folder_location = image.entry.folder_location
            image.notes = image.entry.notes
            image.entry = None
            image.save()


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0002_alter_image_options_remove_image_folder_location_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_images_to_entries, reverse_migration),
    ]
