# Generated by Django 5.2.4 on 2026-01-01 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='reference_tag',
            field=models.ForeignKey(blank=True, help_text="Optional: Reference a tag from the type specified by this tag's TagType", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_by', to='tags.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='value',
            field=models.CharField(blank=True, help_text='Optional value associated with this tag', max_length=100),
        ),
        migrations.AddField(
            model_name='tagtype',
            name='reference_tagtype',
            field=models.ForeignKey(blank=True, help_text='Optional: Allow tags of this type to reference tags from another type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencing_tagtypes', to='tags.tagtype'),
        ),
        migrations.AddConstraint(
            model_name='tagtype',
            constraint=models.CheckConstraint(condition=models.Q(('reference_tagtype', models.F('id')), _negated=True), name='tagtype_no_self_reference'),
        ),
    ]
