# Generated by Django 5.2.4 on 2026-01-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_tagtype_show_in_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagtype',
            name='set_at_upload',
            field=models.BooleanField(default=False, help_text='Show tags of this type during image upload'),
        ),
    ]
