# Generated by Django 5.2.4 on 2026-01-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_tagtype_set_at_upload'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tagtype',
            name='tagtype_no_self_reference',
        ),
        migrations.RemoveField(
            model_name='tagtype',
            name='reference_tagtype',
        ),
        migrations.AddField(
            model_name='tagtype',
            name='reference_tagtypes',
            field=models.ManyToManyField(blank=True, help_text='Optional: Allow tags of this type to reference tags from other types', related_name='referencing_tagtypes', to='tags.tagtype'),
        ),
    ]
