# Generated by Django 5.2.4 on 2026-01-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_remove_tagtype_tagtype_no_self_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='reference_tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='reference_tags',
            field=models.ManyToManyField(blank=True, help_text="Optional: Reference tags from the types specified by this tag's TagType", related_name='referenced_by', to='tags.tag'),
        ),
    ]
